---
title: "fluoroprobe_analysis"
author: "Catarina Pien"
date: '2022-09-13'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Notes from Ted: 
I’ve attached the FluoroProbe data from 2022 that you requested, as both a CSV and an .RData file. You can find the scripts and the raw data that we used in EMP’s GitHub (link here). The script we used is called “FP_data_join.R” and was jointly written by myself and Sarah Perry (cc’d). Sarah wrote the code that bins each data point into a region (they used Brian Mahardja’s EDSM subregions). The data is averaged in 1 minute increments and includes our EXO2 sonde data and the FluoroProbe. The units for the sonde data are as follows:
•	Water Temp = degrees Celsius
•	pH = pH units
•	Specific Conductance = microsiemens per centimenter (uS/cm)
•	Chlorophyll a = both ug/L (FLUOR) and relative fluorescence units (FLUORRFU)
•	Turbidity = FNU
•	DO = both mg/L (DO) and % saturation (DOSAT)

Another thing you’ll notice is that some of the months have NA values for the FluoroProbe. This is because the probe was either malfunctioning that day or was inadvertently left off during the day’s run. 

Just an additional piece of info: for last year’s report we sent our data to USGS so they could use Tableau to generate maps that interpolated values across the whole of individual water bodies like Franks Tract, rather than just making plots showing each data point on a map. Keith B-G would be the one who would know how to get that done. 
