---
title: "plot_phytoplankton"
author: "Catarina Pien"
date: '2022-11-02'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(readxl)
library(dplyr)
library(ggplot2)
library(lubridate)
library(readr)
library(tidyr)
library(sf)
library(deltamapr)
library(ggspatial)
library(viridis)
```

Read data
```{r}
phyto <- read_excel(here::here("analysis_2022", "data_raw", "EMP_Phytoplankton_Jan-Sept-2022.xlsx")) %>%
  janitor::clean_names(case = "upper_camel") %>%
  filter(FullCode != "D19 Microcystis Tow",
         StationCode!= "D19 MC Tow") %>%
  select(Date = SampleDate,
         Station = StationCode,
         AlgalType,
         Genus,
         UnitAbundance = UnitAbundanceNumberOfNaturalUnits,
         OrganismsPerML)

# 2021 combined data
load(here::here("analysis_2022", "data_raw", "EMPPHyto.RData"))
phyto_2021 <- phyto_edb %>%
  filter(Year != "2022") %>%
  select(Date, Station, AlgalType, Genus, UnitAbundance = Count, OrganismsPerML = OrganismsPerMl)

phyto_all <- rbind(phyto, phyto_2021)

emp_stations <- read_csv(here("analysis_2022", "data_raw", "stations_emp.csv"))
load(here("data/Regions.RData"))
```

```{r}
phyto_test <- phyto_region %>%
  mutate(year = factor(year(Date)),
         month = factor(month(Date)))%>%
  filter(CountperML >0) %>%
  filter(Genus %in% c("Aphanizomenon", "Anabaena", "Dolichospermum",
                      "Microcystis", "Oscillatoria", "Cylindrospermopsis",  "Anabaenopsis",
                      "Planktothrix")) %>%
  mutate(Genus = case_when(Genus == "Anabaena" ~"Dolichospermum",
                           TRUE ~ Genus)) %>%
  arrange(Date)
write_csv(phyto_test, "analysis_2022/phyto_data_emp_multiyear_filtered.csv")

# Look at original data - where is the high Microcystis coming from? 
phyto_orig <- phyto %>%
  filter(Genus %in% c("Aphanizomenon", "Anabaena", "Dolichospermum",
                      "Microcystis", "Oscillatoria", "Cylindrospermopsis",  "Anabaenopsis",
                      "Planktothrix")) %>%
  mutate(Genus = case_when(Genus == "Anabaena" ~"Dolichospermum",
                           TRUE ~ Genus)) 
write_csv(phyto_orig, "phyto_data_emp_filtered.csv")

ggplot(phyto_orig) + geom_col(aes(x = factor(month(Date)), y = OrganismsPerML, fill = Genus)) + facet_wrap(~Station) + theme_bw()

ggplot(phyto_test) + geom_col(aes(x = factor(month(Date)), y = OrganismsPerML)) + facet_wrap(~year)

ggplot(phyto_test) + geom_col(aes(x = year, y = OrganismsPerML))
ggplot(phyto_edb) + geom_col(aes(x = Year, y = OrganismsPerMl))

ggplot(phyto_full) + geom_col(aes(x = fYear, y = CountperML))
ggplot(phyto_region) + geom_col(aes(x = fYear, y = CountperML))

franks <- phyto_2022 %>%
  filter(Stratum2 == "Franks",
         fMonth == "Aug")

franks2021 <- phyto_2021 %>%
  filter(Stratum2 == "Franks",
         fMonth == "Jul")
```



# Clean up data
```{r}
phyto_sta <- left_join(phyto_all, emp_stations) %>%
  filter(!is.na(Latitude)) %>%
  filter()

phyto_tax <- phyto %>%
  select(AlgalType, Genus) %>%
  distinct() 
```

Add Zeroes
```{r}
phyto_full = pivot_wider(phyto_sta, id_cols = c("Station", "Date", "Latitude", "Longitude"), names_from = "Genus",
                         values_from = "OrganismsPerML", values_fill = 0, values_fn = sum) %>%
  pivot_longer(cols = "Achnanthidium":last_col(), names_to = "Genus", values_to = "CountperML") %>%
  mutate(Month = month(Date),
         fMonth = month(Date, label = TRUE),
         Year = year(Date),
         fYear = factor(Year)) %>%
  left_join(phyto_tax)
```

Add spatial designation and merge with regions
```{r}
phyto_sf <- st_as_sf(phyto_full, coords = c("Longitude", "Latitude"), crs = 4326) 
phyto_region <- st_intersection(phyto_sf, reg3)
```

```{r}
saveRDS(phyto_region, here("analysis_2022","data_clean", "emp_phyto_data_through2022.rds"))
phyto_region <- readRDS(here("analysis_2022","data_clean", "emp_phyto_data_through2022.rds"))
```


# Plot data

```{r}
phyto_2022 <- filter(phyto_region, fYear == "2022")
phyto_2021 <- filter(phyto_region, fYear == "2021")
```

## All
```{r}
ggplot(phyto_2022, aes(x = Station, y = CountperML, fill = AlgalType))+ geom_col()+facet_wrap(~fMonth)+ scale_fill_brewer(palette = "Set3") + theme_bw()
ggplot(phyto_2022, aes(x = fMonth, y = CountperML, fill = AlgalType))+ geom_col()+facet_wrap(~Stratum, scales = "free_y")+ scale_fill_brewer(palette = "Set3") + theme_bw()
ggplot(phyto_2021, aes(x = fMonth, y = CountperML, fill = AlgalType))+ geom_col()+facet_wrap(~Stratum, scales = "free_y")+ scale_fill_brewer(palette = "Set3") + theme_bw()
```

## No cyanobacteria
```{r}
data_nocy <- phyto_region %>% filter(AlgalType != "Cyanobacterium")

ggplot(data_nocy, aes(x = Stratum, y = CountperML, fill = AlgalType))+
  geom_col()+facet_grid(Year~fMonth) + theme_bw() + theme(axis.text.x = element_text(angle = 90))

ggplot(data_nocy, aes(x = fMonth, y = CountperML, fill = AlgalType))+
  geom_col()+facet_wrap(~Stratum) + theme_bw()
```

# Harmful species only
```{r}
data_HAB = phyto_region %>%
  filter(Genus %in% c("Aphanizomenon", "Anabaena", "Dolichospermum",
                      "Microcystis", "Oscillatoria", "Cylindrospermopsis",  "Anabaenopsis",
                      "Planktothrix"), !is.na(Stratum)) %>%
  mutate(Genus = case_when(Genus == "Anabaena" ~"Dolichospermum",
                           TRUE ~ Genus)) %>%
  st_drop_geometry() 

# Calculate mean by month - genus
HAB_mean = data_HAB %>%
  group_by(Stratum2, Month, fMonth, Year, fYear, Genus) %>%
  summarize(CountperML = mean(CountperML))

HAB_annualmean = data_HAB %>%
  filter(Month %in% c(1, 2, 3, 4,5,6,7,8,9,10)) %>%
   group_by(Stratum2, Year, fYear, Genus) %>%
  summarize(CountperML = mean(CountperML))

# Plots --------------------------------------------------------------------
ggplot(HAB_mean, aes(x = Year, y = CountperML, fill = Genus))+
  geom_col(position = "dodge")+facet_wrap(~Stratum2) + scale_y_log10()+
  ylab("Organisms per mL") + theme_bw()+ theme(legend.position = "bottom")+
  scale_x_continuous(breaks = c(0,4,8,12))

ggplot(HAB_mean, aes(x = Stratum2, y = CountperML, fill = Genus))+
  geom_col()+facet_wrap(~Year) +
  ylab("Organisms per mL") + theme_bw()+ theme(legend.position = "bottom")+
  theme(axis.text.x = element_text(angle = 90))#+
 # scale_x_continuous(breaks = c(2,6,10), labels = c("Feb", "Jun", "Oct"))

ggplot(filter(HAB_mean, Genus != "Microcystis"), aes(x = fMonth, y = CountperML, fill = Genus))+
  geom_col()+facet_grid(~Stratum2, scales = "free_y") +
  theme(legend.position = "top") + theme_bw() +
  theme(axis.text.x = element_text(angle = 90))

```


Figure 2-29 
```{r}
ggplot(HAB_mean, aes(x = fMonth, y = CountperML, fill = Genus))+
  geom_col(position = "fill")+
  facet_wrap(~Stratum2) +
  ylab("Proportion") + 
  theme_bw()+ 
  theme(legend.position = "bottom")
  #scale_x_discrete(breaks = c(2,6,10), labels = c("Feb", "Jun", "Oct"))

# Good for monthly trends
(monthly_trends_2022 <- ggplot(HAB_mean %>% filter(fYear == "2022"), 
                               aes(x = fMonth, y = CountperML, fill = Genus))+
  geom_col()+
  facet_wrap(~Stratum2, scales = "free_y") +
  labs(x = "Month", y = "Organisms per mL") +
  scale_fill_viridis(discrete = TRUE, option = "turbo") +
  theme_bw()+ 
  theme(legend.position = "top",
        axis.text.x = element_text(angle = 90),
        axis.title.x = element_blank()) )

#I think this is the one I want to use
(plot_phytoplankton_year <- ggplot(HAB_annualmean, aes(x = fYear, y = CountperML, fill = Genus))+
  geom_col()+
  facet_grid(Genus~Stratum2, scales = "free_y") +
  labs(x = "Year", y = "Organisms per mL") +
  theme_bw()+ 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, hjust = 1),
        axis.title.x = element_blank()) +
  scale_fill_viridis(discrete = TRUE, option = "turbo", guide = NULL))
```

```{r}
ggplot(HAB_mean %>% filter(fYear %in% c("2015", "2020", "2021", "2022"))) + geom_tile(aes(x = fMonth, y = Stratum2, fill = CountperML)) + facet_wrap(~Genus, scales = "free_y") +
  scale_fill_viridis(option = "plasma") +
  facet_wrap(~fYear) +
  theme_bw()
```

```{r}
png(filename = here("analysis_2022", "figures", "plot_phytoplankton_month_2022.png"), width = 8, height = 6, units = "in", pointsize = 12, family = "sans", res = 300)
monthly_trends_2022
dev.off()

png(filename = here("analysis_2022", "figures", "plot_phytoplankton_year.png"), width = 8.5, height = 9.5, units = "in", pointsize = 12, family = "sans", res = 300)
plot_phytoplankton_year
dev.off()
```

